name: tzurba_roeah_ruchani_app
description: App built by BMDC students for Tzurba M'Rabanan
version: 0.0.1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  cupertino_icons: ^0.1.2
  google_fonts: ^0.3.2
  page_transition: ^1.1.5
  firebase_auth: ^0.15.4
  google_sign_in: ^4.1.1
  cloud_functions: ^0.4.1+8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true